WIP first try.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,11 +1,8 @@
 version: 2.1
 
-orbs:
-  aws-s3: circleci/aws-s3@1.0.11
-
 executors:
   default:
-    working_directory: /go/src/github.com/mattermost/mattermost-push-proxy
+    working_directory: /go/src/github.com/worldr/push-proxy
     docker:
       - image: circleci/golang:1.13
 
@@ -46,46 +43,28 @@ jobs:
           command: |
             ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./dist/mattermost-push-proxy.tar.gz
 
-  publish-release-s3:
-    docker:
-    - image: 'circleci/python:2.7'
-    steps:
-      - attach_workspace:
-          at: .
-      - run: |
-          set -e
-          set -u
-          if [[ -z "${CIRCLE_TAG:-}" ]]; then
-            echo "not a tag, aborting..."
-            exit 1
-          fi
-      - aws-s3/copy:
-          from: ./dist/mattermost-push-proxy.tar.gz
-          to: s3://releases.mattermost.com/mattermost-push-proxy/$CIRCLE_TAG/
-          arguments: --acl public-read --cache-control "no-cache"
-
-
-  push-docker:
-    executor:
-      name: default
-    steps:
-      - checkout
-      - setup_remote_docker
-      - run: |
-          set -e
-          set -u
-          if [[ -z "${CIRCLE_TAG:-}" ]]; then
-            echo "not a tag, aborting..."
-            exit 1
-          else
-            echo "Pushing release $CIRCLE_TAG..."
-            TAG="${CIRCLE_TAG//v}"
-          fi
-          APP_VERSION=$TAG
-          cd docker
-          docker build --rm --no-cache -t mattermost/mattermost-push-proxy:latest -t mattermost/mattermost-push-proxy:$TAG .
-          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
-          docker push mattermost/mattermost-push-proxy
+# This is a great idea as soon as we have a Docker repository.
+#  push-docker:
+#    executor:
+#      name: default
+#    steps:
+#      - checkout
+#      - setup_remote_docker
+#      - run: |
+#          set -e
+#          set -u
+#          if [[ -z "${CIRCLE_TAG:-}" ]]; then
+#            echo "not a tag, aborting..."
+#            exit 1
+#          else
+#            echo "Pushing release $CIRCLE_TAG..."
+#            TAG="${CIRCLE_TAG//v}"
+#          fi
+#          APP_VERSION=$TAG
+#          cd docker
+#          docker build --rm --no-cache -t mattermost/mattermost-push-proxy:latest -t mattermost/mattermost-push-proxy:$TAG .
+#          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
+#          docker push mattermost/mattermost-push-proxy
 
 workflows:
   version: 2
@@ -125,21 +104,12 @@ workflows:
               only: /^v.*/
             branches:
               ignore: /.*/
-      - publish-release-s3:
-          context: mattermost-release-s3
-          requires:
-            - build
-          filters:
-            tags:
-              only: /^v.*/
-            branches:
-              ignore: /.*/
-      - push-docker:
-          context: matterbuild-docker
-          requires:
-            - publish-github-release
-          filters:
-            tags:
-              only: /^v.*/
-            branches:
-              ignore: /.*/
+      # - push-docker:
+      #     context: matterbuild-docker
+      #     requires:
+      #       - publish-github-release
+      #     filters:
+      #       tags:
+      #         only: /^v.*/
+      #       branches:
+      #         ignore: /.*/
